---
roles: []

mail_domain: meinzeltlager.com
mail_hostname: mail.meinzeltlager.com

postfix_db_name: postfix_db

postfix_settings:
  mynetworks: 127.0.0.1/32 [::1]/128
  myhostname: "{{ mail_hostname }}"
  mydomain: "{{ mail_domain }}"
  myorigin: $mydomain
  # was $mydomain
  mydestination: localhost
  mynetworks_style: host
  tls_ssl_options: NO_COMPRESSION
  tls_high_cipherlist: 'EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA'

  maximal_queue_lifetime: 1h
  bounce_queue_lifetime: 1h
  maximal_backoff_time: 15m
  minimal_backoff_time: 5m
  queue_run_delay: 5m


  relay_domains: $mydestination
  virtual_mailbox_base: /var/mail/vmail
  virtual_mailbox_limit: 512000000
  virtual_minimum_uid: 5000
  virtual_uid_maps: static:5000
  virtual_gid_maps: static:5000
  local_transport: virtual
  transport_maps: hash:/etc/postfix/transport

  # Dovecot
  virtual_transport: lmtp:unix:private/dovecot-lmtp

  # Spamfilter, DKIM-signatures
  smtpd_milters: inet:127.0.0.1:11332
  non_smtpd_milters: inet:127.0.0.1:11332
  milter_protocol: 6
  milter_mail_macros: i {mail_addr} {client_addr} {client_name} {auth_authen}
  milter_default_action: accept

  # Restrictions for relay
  smtpd_relay_restrictions: |
    reject_non_fqdn_recipient
    reject_unknown_recipient_domain
    permit_mynetworks
    reject_unauth_destination
  smtpd_client_restrictions: |
    check_client_access hash:/etc/postfix/without_ptr
  #reject_unknown_client_hostname
  smtpd_helo_required: 'yes'
  smtpd_helo_restrictions: |
    permit_mynetworks
    reject_invalid_helo_hostname
    reject_non_fqdn_helo_hostname
  #reject_unknown_helo_hostname
  smtpd_data_restrictions: reject_unauth_pipelining

  mua_relay_restrictions: reject_non_fqdn_recipient,reject_unknown_recipient_domain,permit_sasl_authenticated,reject
  mua_sender_restrictions: reject_non_fqdn_sender,reject_sender_login_mismatch,permit_sasl_authenticated,reject
  mua_client_restrictions: permit_sasl_authenticated,reject

  # Postscreen
  postscreen_access_list: cidr:/etc/postfix/postscreen_access
  postscreen_blacklist_action: drop
  postscreen_greet_action: drop
  postscreen_dnsbl_threshold: 2
  postscreen_dnsbl_sites: |
    ix.dnsbl.manitu.net*2
    zen.spamhaus.org*2
  #postscreen_dnsbl_action: drop
  postscreen_dnsbl_action: ignore

  # Incoming
  smtpd_recipient_restrictions: check_recipient_access pgsql:/etc/postfix/sql/recipient-access.cf
  smtpd_tls_security_level: may
  smtpd_tls_auth_only: 'yes'
  smtpd_tls_received_header: 'yes'
  smtpd_tls_cert_file: '{{ acme_path }}/sites/{{ mail_hostname }}/{{ mail_hostname }}.crt'
  smtpd_tls_key_file: '{{ acme_path }}/sites/{{ mail_hostname }}/{{ mail_hostname }}.key'
  smtpd_tls_dh1024_param_file: ${config_directory}/dhparams.pem
  smtpd_tls_protocols: '!SSLv2, !SSLv3'
  smtpd_tls_ciphers: high
  smtpd_tls_session_cache_database: 'btree:${data_directory}/smtpd_scache'
  smtpd_tls_exclude_ciphers: aNULL, eNULL, EXPORT, DES, RC4, MD5, PSK, aECDH, EDH-DSS-DES-CBC3-SHA, EDH-RSA-DES-CBC3-SHA, KRB5-DES, CBC3-SHA

  # Outgoing
  smtp_tls_security_level: dane
  smtp_dns_support_level: dnssec
  smtp_tls_policy_maps: pgsql:/etc/postfix/sql/tls-policy.cf
  smtp_tls_session_cache_database: 'btree:${data_directory}/smtp_scache'
  smtp_tls_protocols: '!SSLv2, !SSLv3'
  smtp_tls_ciphers: 'high'

  # Maps
  virtual_alias_maps: |
    pgsql:/etc/postfix/sql/aliases.cf
    pgsql:/etc/postfix/sql/regex_aliases.cf
  virtual_mailbox_maps: pgsql:/etc/postfix/sql/accounts.cf
  virtual_mailbox_domains: pgsql:/etc/postfix/sql/domains.cf
  local_recipient_maps: $virtual_mailbox_maps

  # Done by dovecot
  mailbox_size_limit: 0
  message_size_limit: 5242880
  biff: 'no'
  append_dot_mydomain: 'no'
  recipient_delimiter: +

postgresql_locale: en_US.utf8

caddy_conf_dir: /etc/caddy

caddy_includes:
  defaults: |
    header / Content-Security-Policy "default-src 'self' data: ws:; form-action 'self'; frame-ancestors 'self'"
    header / Referrer-Policy "no-referrer-when-downgrade"
    header / X-Content-Type-Options "nosniff"
    header / X-Download-Options "noopen"
    header / X-Frame-Options "SAMEORIGIN"
    header / X-Permitted-Cross-Domain-Policies "none"
    header / X-Robots-Tag "none"
    header / X-XSS-Protection "1; mode=block"
    errors stderr

  ssl_defaults: |
    header / Strict-Transport-Security "max-age=2592000; includeSubDomains" # 30d

enable_autoupdate: True
sshd_host_settings: []
sshd_settings:
  - regexp: "^#?Port "
    line: "Port {{ sshd_port }}"
  - regexp: "^#?PermitRootLogin "
    line: PermitRootLogin no
  - regexp: "^#?MaxAuthTries "
    line: MaxAuthTries 1
  - regexp: "^#?PasswordAuthentication "
    line: PasswordAuthentication no
  - regexp: "^#?AllowAgentForwarding "
    line: AllowAgentForwarding no
  - regexp: "^#?PermitTunnel "
    line: PermitTunnel yes

powerdns_master: False

zeltlager_error_message: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30376432343638643739356137323138653565653936303236386136373836663334623336653939
  6430376430303736373432386566636666613930343734380a343065343733633733376633323461
  31373733616233323633353731346535306534373734353136376138373331663537613662393033
  3034656631646436320a396262323138393638363837656532326230306334636435346666656431
  32643339303565363539393761373463356636643961663738366439333437333937393832623038
  65666533356466646365346330353961656263323736313735636434343637373932313162623830
  633036616534396566663832626164663739

sshd_port: 4242
phpmyadmin_port: 8080
zeltlager_website_port: 9007
