---
- hosts: all
  tasks:
    - include_role:
        name: weareinteractive.sudo
      vars:
        sudo_sudoers_file: '10_wheel'
        sudo_defaults:
          - defaults: insults
        sudo_users:
          - name: '%wheel'
          - name: ansible
            nopasswd: True
      tags: sudo
    - import_role:
        name: defaults
      tags: defaults
      when: "'defaults' in roles"
    - import_role:
        name: sshd
      tags: sshd
      when: "'sshd' in roles"
    - import_role:
        name: nftables
      tags: nftables
      when: "'nftables' in roles"
    - import_role:
        name: wireguard
      tags: wireguard
      when: "'wireguard' in roles"
    - import_role:
        name: prometheus
      tags: prometheus
      when: "'prometheus' in roles"
    - import_role:
        name: prometheus_script_exporter
      tags: prometheus_script_exporter
      when: "'prometheus_script_exporter' in roles"
    - import_role:
        name: prometheus_telegram_bot
      tags: prometheus_telegram_bot
      when: "'prometheus_telegram_bot' in roles"
    - import_role:
        name: postgresql
      tags: postgresql
      when: "'postgresql' in roles"
    - import_role:
        name: caddy
      tags: caddy
      when: "'caddy' in roles"
    - import_role:
        name: mail
      tags: mail
      when: "'mail' in roles"
    - import_role:
        name: php
      tags: php
      when: "'php' in roles"
    - import_role:
        name: mysql
      tags: mysql
      when: "'mysql' in roles"
    - import_role:
        name: phpmyadmin
      tags: phpmyadmin
      when: "'phpmyadmin' in roles"
    - import_role:
        name: mediawiki
      tags: mediawiki
      when: "'mediawiki' in roles"
    - import_role:
        name: zeltlager_website
      tags: zeltlager_website
      when: "'zeltlager_website' in roles"
    - import_role:
        name: zeltlager_app
      tags: zeltlager_app
      when: "'zeltlager_app' in roles"
    - import_role:
        name: sentry
      tags: sentry
      when: "'sentry' in roles"
